/****************************************************************************/
/*  Hyper Operating System V4  μITRON4.0仕様 Real-Time OS                  */
/*      例外処理（割込み）定義                                              */
/*                                                                          */
/*                                  Copyright (C) 1998-2008 by Project HOS  */
/*                                  http://sourceforge.jp/projects/hos/     */
/****************************************************************************/
#ifndef	__vect_h__
#define	__vect_h__

#define	HOS_VN_ExcCode0		(5)
#define	HOS_VN_ExcCode1		(6)
#define	HOS_VN_ExcCode2		(7)
#define	HOS_VN_ExcCode3		(8)
#define	HOS_VN_ExcCode4		(9)
#define	HOS_VN_ExcCode5		(10)
#define	HOS_VN_ExcCode6		(11)
#define	HOS_VN_ExcCode7		(12)
#define	HOS_VN_ExcCode8		(13)
#define	HOS_VN_ExcCode9		(14)
#define	HOS_VN_ExcCode10	(15)
#define	HOS_VN_ExcCode11	(16)
#define	HOS_VN_ExcCode12	(17)
#define	HOS_VN_ExcCode13	(18)
#define	HOS_VN_ExcCode14	(19)
#define	HOS_VN_ExcCode15	(20)
#define	HOS_VN_ExcCode16	(21)
#define	HOS_VN_ExcCode17	(22)
#define	HOS_VN_ExcCode18	(23)
#define	HOS_VN_ExcCode19	(24)
#define	HOS_VN_ExcCode20	(25)
#define	HOS_VN_ExcCode21	(26)
#define	HOS_VN_ExcCode22	(27)
#define	HOS_VN_ExcCode23	(28)
#define	HOS_VN_ExcCode24	(29)
#define	HOS_VN_ExcCode25	(30)
#define	HOS_VN_ExcCode26	(31)
#define	HOS_VN_ExcCode27	(32)
#define	HOS_VN_ExcCode28	(33)
#define	HOS_VN_ExcCode29	(34)
#define	HOS_VN_ExcCode30	(35)
#define	HOS_VN_ExcCode31	(36)
#define	HOS_VN_IP7			(37)
#define	HOS_VN_IP6			(38)
#define	HOS_VN_IP5			(39)
#define	HOS_VN_IP4			(40)
#define	HOS_VN_IP3			(41)
#define	HOS_VN_IP2			(42)
#define	HOS_VN_IP1			(43)
#define	HOS_VN_IP0			(44)
#define	HOS_VN_SYSCALL		(45)
/* VR9721, UX1200E */
#define	HOS_VN_TC7			(64)
#define	HOS_VN_TC6			(65)
#define	HOS_VN_TC5			(66)
#define	HOS_VN_TC4			(67)
#define	HOS_VN_TC3			(68)
#define	HOS_VN_TC2			(69)
#define	HOS_VN_TC1			(70)
#define	HOS_VN_TC0			(71)
#define	HOS_VN_CSI			(72)
#define	HOS_VN_CSIEMP		(73)
#define	HOS_VN_CSIOVF		(74)
#define	HOS_VN_UART1TO		(75)
#define	HOS_VN_UART1		(76)
#define	HOS_VN_UART2TO		(77)
#define	HOS_VN_UART2		(78)
/* SEMB1200A */
#define	HOS_VN_PWM0			(112)
#define	HOS_VN_PWM1			(113)
#define	HOS_VN_PWM2			(114)
#define	HOS_VN_PWM3			(115)
#define	HOS_VN_UART30		(116)
#define	HOS_VN_UART31		(117)
#define	HOS_VN_UART32		(118)
#define	HOS_VN_UART33		(119)
#define	HOS_VN_UART34		(120)
#define	HOS_VN_UART35		(121)
#define	HOS_VN_UART36		(122)
#define	HOS_VN_UART37		(123)

#define	HOS_VA_BASE			(0x80000000)
#define	HOS_VA_ExcCode0		(0x0614)
#define	HOS_VA_ExcCode1		(0x0618)
#define	HOS_VA_ExcCode2		(0x061C)
#define	HOS_VA_ExcCode3		(0x0620)
#define	HOS_VA_ExcCode4		(0x0624)
#define	HOS_VA_ExcCode5		(0x0628)
#define	HOS_VA_ExcCode6		(0x062C)
#define	HOS_VA_ExcCode7		(0x0630)
#define	HOS_VA_ExcCode8		(0x0634)
#define	HOS_VA_ExcCode9		(0x0638)
#define	HOS_VA_ExcCode10	(0x063C)
#define	HOS_VA_ExcCode11	(0x0640)
#define	HOS_VA_ExcCode12	(0x0644)
#define	HOS_VA_ExcCode13	(0x0648)
#define	HOS_VA_ExcCode14	(0x064C)
#define	HOS_VA_ExcCode15	(0x0650)
#define	HOS_VA_ExcCode16	(0x0654)
#define	HOS_VA_ExcCode17	(0x0658)
#define	HOS_VA_ExcCode18	(0x065C)
#define	HOS_VA_ExcCode19	(0x0660)
#define	HOS_VA_ExcCode20	(0x0664)
#define	HOS_VA_ExcCode21	(0x0668)
#define	HOS_VA_ExcCode22	(0x066C)
#define	HOS_VA_ExcCode23	(0x0670)
#define	HOS_VA_ExcCode24	(0x0674)
#define	HOS_VA_ExcCode25	(0x0678)
#define	HOS_VA_ExcCode26	(0x067C)
#define	HOS_VA_ExcCode27	(0x0680)
#define	HOS_VA_ExcCode28	(0x0684)
#define	HOS_VA_ExcCode29	(0x0688)
#define	HOS_VA_ExcCode30	(0x068C)
#define	HOS_VA_ExcCode31	(0x0690)
#define	HOS_VA_IP7			(0x0694)
#define	HOS_VA_IP6			(0x0698)
#define	HOS_VA_IP5			(0x069C)
#define	HOS_VA_IP4			(0x06A0)
#define	HOS_VA_IP3			(0x06A4)
#define	HOS_VA_IP2			(0x06A8)
#define	HOS_VA_IP1			(0x06AC)
#define	HOS_VA_IP0			(0x06B0)
#define	HOS_VA_SYSCALL		(0x06B4)
/* VR9721, UX1200E */
#define	HOS_VA_TC7			(0x0700)
#define	HOS_VA_TC6			(0x0704)
#define	HOS_VA_TC5			(0x0708)
#define	HOS_VA_TC4			(0x070C)
#define	HOS_VA_TC3			(0x0710)
#define	HOS_VA_TC2			(0x0714)
#define	HOS_VA_TC1			(0x0718)
#define	HOS_VA_TC0			(0x071C)
#define	HOS_VA_CSI			(0x0720)
#define	HOS_VA_CSIEMP		(0x0724)
#define	HOS_VA_CSIOVF		(0x0728)
#define	HOS_VA_UART1TO		(0x072C)
#define	HOS_VA_UART1		(0x0730)
#define	HOS_VA_UART2TO		(0x0734)
#define	HOS_VA_UART2		(0x0738)
/* SEMB1200A */
#define	HOS_VA_PWM0			(0x07C0)
#define	HOS_VA_PWM1			(0x07C4)
#define	HOS_VA_PWM2			(0x07C8)
#define	HOS_VA_PWM3			(0x07CC)
#define	HOS_VA_UART30		(0x07D0)
#define	HOS_VA_UART31		(0x07D4)
#define	HOS_VA_UART32		(0x07D8)
#define	HOS_VA_UART33		(0x07DC)
#define	HOS_VA_UART34		(0x07E0)
#define	HOS_VA_UART35		(0x07E4)
#define	HOS_VA_UART36		(0x07E8)
#define	HOS_VA_UART37		(0x07EC)

#define	HOS_VECT_ExcCode0	(HOS_VA_BASE | HOS_VA_ExcCode0)
#define	HOS_VECT_ExcCode1	(HOS_VA_BASE | HOS_VA_ExcCode1)
#define	HOS_VECT_ExcCode2	(HOS_VA_BASE | HOS_VA_ExcCode2)
#define	HOS_VECT_ExcCode3	(HOS_VA_BASE | HOS_VA_ExcCode3)
#define	HOS_VECT_ExcCode4	(HOS_VA_BASE | HOS_VA_ExcCode4)
#define	HOS_VECT_ExcCode5	(HOS_VA_BASE | HOS_VA_ExcCode5)
#define	HOS_VECT_ExcCode6	(HOS_VA_BASE | HOS_VA_ExcCode6)
#define	HOS_VECT_ExcCode7	(HOS_VA_BASE | HOS_VA_ExcCode7)
#define	HOS_VECT_ExcCode8	(HOS_VA_BASE | HOS_VA_ExcCode8)
#define	HOS_VECT_ExcCode9	(HOS_VA_BASE | HOS_VA_ExcCode9)
#define	HOS_VECT_ExcCode10	(HOS_VA_BASE | HOS_VA_ExcCode10)
#define	HOS_VECT_ExcCode11	(HOS_VA_BASE | HOS_VA_ExcCode11)
#define	HOS_VECT_ExcCode12	(HOS_VA_BASE | HOS_VA_ExcCode12)
#define	HOS_VECT_ExcCode13	(HOS_VA_BASE | HOS_VA_ExcCode13)
#define	HOS_VECT_ExcCode14	(HOS_VA_BASE | HOS_VA_ExcCode14)
#define	HOS_VECT_ExcCode15	(HOS_VA_BASE | HOS_VA_ExcCode15)
#define	HOS_VECT_ExcCode16	(HOS_VA_BASE | HOS_VA_ExcCode16)
#define	HOS_VECT_ExcCode17	(HOS_VA_BASE | HOS_VA_ExcCode17)
#define	HOS_VECT_ExcCode18	(HOS_VA_BASE | HOS_VA_ExcCode18)
#define	HOS_VECT_ExcCode19	(HOS_VA_BASE | HOS_VA_ExcCode19)
#define	HOS_VECT_ExcCode20	(HOS_VA_BASE | HOS_VA_ExcCode20)
#define	HOS_VECT_ExcCode21	(HOS_VA_BASE | HOS_VA_ExcCode21)
#define	HOS_VECT_ExcCode22	(HOS_VA_BASE | HOS_VA_ExcCode22)
#define	HOS_VECT_ExcCode23	(HOS_VA_BASE | HOS_VA_ExcCode23)
#define	HOS_VECT_ExcCode24	(HOS_VA_BASE | HOS_VA_ExcCode24)
#define	HOS_VECT_ExcCode25	(HOS_VA_BASE | HOS_VA_ExcCode25)
#define	HOS_VECT_ExcCode26	(HOS_VA_BASE | HOS_VA_ExcCode26)
#define	HOS_VECT_ExcCode27	(HOS_VA_BASE | HOS_VA_ExcCode27)
#define	HOS_VECT_ExcCode28	(HOS_VA_BASE | HOS_VA_ExcCode28)
#define	HOS_VECT_ExcCode29	(HOS_VA_BASE | HOS_VA_ExcCode29)
#define	HOS_VECT_ExcCode30	(HOS_VA_BASE | HOS_VA_ExcCode30)
#define	HOS_VECT_ExcCode31	(HOS_VA_BASE | HOS_VA_ExcCode31)
#define	HOS_VECT_IP7		(HOS_VA_BASE | HOS_VA_IP7)
#define	HOS_VECT_IP6		(HOS_VA_BASE | HOS_VA_IP6)
#define	HOS_VECT_IP5		(HOS_VA_BASE | HOS_VA_IP5)
#define	HOS_VECT_IP4		(HOS_VA_BASE | HOS_VA_IP4)
#define	HOS_VECT_IP3		(HOS_VA_BASE | HOS_VA_IP3)
#define	HOS_VECT_IP2		(HOS_VA_BASE | HOS_VA_IP2)
#define	HOS_VECT_IP1		(HOS_VA_BASE | HOS_VA_IP1)
#define	HOS_VECT_IP0		(HOS_VA_BASE | HOS_VA_IP0)
#define	HOS_VECT_SYSCALL	(HOS_VA_BASE | HOS_VA_SYSCALL)
#define	HOS_VECT_TC7		(HOS_VA_BASE | HOS_VA_TC7)
#define	HOS_VECT_TC6		(HOS_VA_BASE | HOS_VA_TC6)
#define	HOS_VECT_TC5		(HOS_VA_BASE | HOS_VA_TC5)
#define	HOS_VECT_TC4		(HOS_VA_BASE | HOS_VA_TC4)
#define	HOS_VECT_TC3		(HOS_VA_BASE | HOS_VA_TC3)
#define	HOS_VECT_TC2		(HOS_VA_BASE | HOS_VA_TC2)
#define	HOS_VECT_TC1		(HOS_VA_BASE | HOS_VA_TC1)
#define	HOS_VECT_TC0		(HOS_VA_BASE | HOS_VA_TC0)
#define	HOS_VECT_CSI		(HOS_VA_BASE | HOS_VA_CSI)
#define	HOS_VECT_CSIEMP		(HOS_VA_BASE | HOS_VA_CSIEMP)
#define	HOS_VECT_CSIOVF		(HOS_VA_BASE | HOS_VA_CSIOVF)
#define	HOS_VECT_UART1		(HOS_VA_BASE | HOS_VA_UART1)
#define	HOS_VECT_UART1TO	(HOS_VA_BASE | HOS_VA_UART1TO)
#define	HOS_VECT_UART2		(HOS_VA_BASE | HOS_VA_UART2)
#define	HOS_VECT_UART2TO	(HOS_VA_BASE | HOS_VA_UART2TO)
#define	HOS_VECT_PWM0		(HOS_VA_BASE | HOS_VA_PWM0)
#define	HOS_VECT_PWM1		(HOS_VA_BASE | HOS_VA_PWM1)
#define	HOS_VECT_PWM2		(HOS_VA_BASE | HOS_VA_PWM2)
#define	HOS_VECT_PWM3		(HOS_VA_BASE | HOS_VA_PWM3)
#define	HOS_VECT_UART30		(HOS_VA_BASE | HOS_VA_UART30)
#define	HOS_VECT_UART31		(HOS_VA_BASE | HOS_VA_UART31)
#define	HOS_VECT_UART32		(HOS_VA_BASE | HOS_VA_UART32)
#define	HOS_VECT_UART33		(HOS_VA_BASE | HOS_VA_UART33)
#define	HOS_VECT_UART34		(HOS_VA_BASE | HOS_VA_UART34)
#define	HOS_VECT_UART35		(HOS_VA_BASE | HOS_VA_UART35)
#define	HOS_VECT_UART36		(HOS_VA_BASE | HOS_VA_UART36)
#define	HOS_VECT_UART37		(HOS_VA_BASE | HOS_VA_UART37)

#endif
/* ------------------------------------------------------------------------ */
/*  Copyright (C) 1998-2008 by Project HOS                                  */
/* ------------------------------------------------------------------------ */
